# | Layout |
# layouts | https://mangowm.github.io/docs/window-management/layouts

# Change your layout here for each workspace.
# tile, scroller, grid, deck, monocle, center_tile, vertical_tile, right_tile, vertical_scroller, dwindle, fair, vertical_fair, vertical_grid, vertical_deck

# Scrolling layout settings
scroller_structs = 2
scroller_default_proportion = 0.5
scroller_focus_center = 0
scroller_prefer_center = 0
scroller_prefer_overspread = 1
edge_scroller_pointer_focus = 0
scroller_ignore_proportion_single = 0
scroller_default_proportion_single = 1.0
scroller_proportion_preset =  0.333, 0.5, 0.666

# Master-Stack layout settings
new_is_master = 0
default_mfact = 0.50
default_nmaster = 1
