# | Rules |
# Window/Tag/Layer rules. | https://mangowm.github.io/docs/window-management/rules

tagrule = id:1, layout_name:scroller
tagrule = id:2, layout_name:grid

windowrule = isfloating:1, appid:[Ss]team, tags:3
windowrule = isfloating:0, title:Steam, tags:3
windowrule = isfloating:1, appid:steam, title:Steam Settings, tags:3
windowrule = isfloating:1, appid:goverlay 

layerrule = noanim:1, noblur:1, layer_name:selection
