color0 #2c2c26
color1 #fd4663
color2 #aead9e
color3 #9ea290
color4 #9aa290
color5 #c5c4ba
color6 #c2c5ba
color7 #f3f3f2
color8 #6b6b61
color9 #fd4663
color10 #aead9e
color11 #9ea290
color12 #9aa290
color13 #c5c4ba
color14 #c2c5ba
color15 #f3f3f2

cursor                #f3f3f2
cursor_text_color     #21211c
background            #21211c
foreground            #f3f3f2
selection_foreground  #b5b5b0
selection_background  #2c2c26
active_border_color   #aead9e
inactive_border_color #2c2c26
url_color             #aead9e

active_tab_foreground   #22211c
active_tab_background   #aead9e
inactive_tab_foreground #b5b5b0
inactive_tab_background #2c2c26
cursor_trail_color      #b5b5b0
