color0 #2c2826
color1 #d6aa88
color2 #bbada3
color3 #b9b3a5
color4 #b7b6a7
color5 #c9beb6
color6 #c7c2b7
color7 #f3f2f2
color8 #6d6863
color9 #d6aa88
color10 #bbada3
color11 #b9b3a5
color12 #b7b6a7
color13 #c9beb6
color14 #c7c2b7
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #211e1c
background            #211e1c
foreground            #f3f2f2
selection_foreground  #b5b2b0
selection_background  #2c2826
active_border_color   #bbada3
inactive_border_color #2c2826
url_color             #bbada3

active_tab_foreground   #221e1c
active_tab_background   #bbada3
inactive_tab_foreground #b5b2b0
inactive_tab_background #2c2826
cursor_trail_color      #b5b2b0
